### PR TITLE
Update for V2 API in FreeNAS

### PR DESCRIPTION
**Pull request by kensand**
This updates the script to work with the V2 API for FreeNAS - I recommend pulling into a separate branch (I think you need to create the branch first before I can make the PR to it).

### CODE REVIEW

**Comment by danb35** [comment]
I've created an api-v2 branch--can you change your PR to that branch?  I also merged #19, which cleans up old certificates; I think there will be a few changes needed to your work on that.

**Comment by DasSkelett** [comment]
I've rebased @kensand's work on the current master (52e020b17c1c2ec8223a6d87da2e39da70dc8d38) and changed the new code for the v2 API: https://github.com/DasSkelett/deploy-freenas/tree/feature/api-v2
@kensand, should I do a PR to your branch so you can incorporate the changes and add them to this pull request? Or should I just submit it as new separate PR in this repository targeting the new api-v2 branch, replacing this PR?

**Comment by kensand** [comment]
@DasSkelett would you mind replacing this PR? Tbh, I didn't end up even using FreeNAS for my project, so I don't even have a box to test it on anymore - I'd have to make a VM or something.

**Comment by kensand** [comment]
Closing in favor of #23

**Pull request closed without merging**
